[phases.setup]
nixPkgs = ["php81", "php81Extensions.mysql", "php81Extensions.pdo", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.curl", "php81Extensions.zip", "php81Extensions.gd", "php81Extensions.fileinfo", "php81Extensions.openssl", "php81Extensions.tokenizer", "php81Extensions.json", "php81Extensions.bcmath", "php81Extensions.ctype", "php81Extensions.xmlwriter", "php81Extensions.dom", "php81Extensions.iconv", "php81Extensions.simplexml", "php81Extensions.spl", "php81Extensions.reflection", "php81Extensions.session", "php81Extensions.sodium", "php81Extensions.phar", "php81Extensions.standard", "php81Extensions.calendar", "php81Extensions.exif", "php81Extensions.ftp", "php81Extensions.gettext", "php81Extensions.hash", "php81Extensions.mysqli", "php81Extensions.pdo_mysql", "php81Extensions.pdo_sqlite", "php81Extensions.sqlite3", "php81Extensions.wddx", "php81Extensions.xmlreader", "php81Extensions.xmlrpc", "php81Extensions.xsl", "php81Extensions.zip", "php81Extensions.zlib"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache",
    "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT" 